# Generated by Django 5.0.2 on 2024-02-28 23:50

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AdditionalResponse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("WorkExpDesc", models.CharField(max_length=500, null=True)),
                ("CollegeExpDesc", models.CharField(max_length=500, null=True)),
                ("InPersonInterview", models.CharField(max_length=3)),
                ("FullName", models.CharField(max_length=50, null=True)),
                ("Email", models.EmailField(max_length=50, null=True)),
                ("Phone", models.IntegerField(max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="MainReasons",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("position", models.CharField(max_length=30)),
                ("influence", models.JSONField(default=list)),
                ("additional_reflection", models.CharField(max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="WorkExperienceMetrics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Support_Professional_Development", models.IntegerField()),
                ("Career_Growth_Opportunities", models.IntegerField()),
                ("Accomplishment_Recognition", models.IntegerField()),
                ("Work_Life_Balance_Consideration", models.IntegerField()),
                ("Collegial_Work_Environment", models.IntegerField()),
                ("DEI_Commitment", models.IntegerField()),
                ("College_Diversity", models.IntegerField()),
                ("Department_Diversity", models.IntegerField()),
                ("Mentoring_Opportunities", models.IntegerField()),
                ("Social_Networking_Support", models.IntegerField()),
                ("Contribution_Recognition", models.IntegerField()),
                ("Experience_Valuation", models.IntegerField()),
                ("Collaboration_Opportunities", models.IntegerField()),
                ("Openness_to_New_Ideas", models.IntegerField()),
                ("Integration_into_Community", models.IntegerField()),
                ("Compensation", models.IntegerField()),
                ("Health_Benefits", models.IntegerField()),
                ("Other_College_Benefits", models.IntegerField()),
            ],
        ),
    ]
