# Generated by Django 5.0.2 on 2024-03-08 23:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("survey", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="additionalresponse",
            name="Phone",
            field=models.CharField(
                blank=True,
                max_length=10,
                validators=[django.core.validators.RegexValidator("^\\d{10}$")],
            ),
        ),
    ]
